export const tracks = [
  {
    id: 1,
    title: "Bohemian Rhapsody",
    author: "Queen",
    album: "A Night at the Opera",
    duration: 354,
    artwork: "https://example.com/cover/bohemian100x100.jpg",
    explicit: false,
  },
  {
    id: 2,
    title: "Stairway to Heaven",
    author: "Led Zeppelin",
    album: "Led Zeppelin IV",
    duration: 482,
    artwork: "https://example.com/cover/stairway100x100.jpg",
    explicit: false,
  },
  {
    id: 3,
    title: "Smells Like Teen Spirit",
    author: "Nirvana",
    album: "Nevermind",
    duration: 301,
    artwork: "static/browser/img/logo.jpg",
    explicit: true,
  },
  {
    id: 4,
    title: "Hotel California",
    author: "Eagles",
    album: "Hotel California",
    duration: 391,
    artwork: "https://example.com/cover/hotel100x100.jpg",
    explicit: false,
  },
  {
    id: 5,
    title: "Imagine",
    author: "John Lennon",
    album: "Imagine",
    duration: 183,
    artwork: "https://example.com/cover/imagine100x100.jpg",
    explicit: false,
  },
  {
    id: 6,
    title: "Like a Rolling Stone",
    author: "Bob Dylan",
    album: "Highway 61 Revisited",
    duration: 373,
    artwork: "static/browser/img/logo.jpg",
    explicit: false,
  },
  {
    id: 7,
    title: "Wonderwall",
    author: "Oasis",
    album: "(What's the Story) Morning Glory?",
    duration: 258,
    artwork: "https://example.com/cover/wonderwall100x100.jpg",
    explicit: false,
  },
  {
    id: 8,
    title: "Billie Jean",
    author: "Michael Jackson",
    album: "Thriller",
    duration: 294,
    artwork: "https://example.com/cover/billie100x100.jpg",
    explicit: false,
  },
  {
    id: 9,
    title: "Purple Haze",
    author: "Jimi Hendrix",
    album: "Are You Experienced?",
    duration: 172,
    artwork: "static/browser/img/logo.jpg",
    explicit: false,
  },
  {
    id: 10,
    title: "Lose Yourself",
    author: "Eminem",
    album: "8 Mile Soundtrack",
    duration: 326,
    artwork: "https://example.com/cover/lose100x100.jpg",
    explicit: true,
  },
];

export default tracks;
